---
driver_plugin: vagrant
driver_config:
  http_proxy: http://10.100.3.135:3128
  https_proxy: http://10.100.3.135:3128
  no_proxy: "localhost,127.0.0.1,*.ad.lancscc.net"
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  chef_client:
    http_proxy: http://10.100.3.135:3128
    https_proxy: http://10.100.3.135:3128
    no_proxy: "localhost,127.0.0.1,*.ad.lancscc.net"

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: centos-6.4
   
suites:
  - name: default
    driver_config:
      network:
      - ['forwarded_port', {guest: 80, host: 8081}]
    run_list:
      - recipe[redmine::default]
    attributes:
      mysql:
        server_root_password: 'rootpass'
        server_debian_password: 'debpass'
        server_repl_password: 'replpass'
        bind_address: 'localhost'
      gitlab:
        mysql_password: 'k09vw7wa5s'
    excludes:
      - centos-6.4
