---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: centos-6.4
   
suites:
  - name: default
    driver_config:
      network:
      - ["public_network"]
    run_list:
      - recipe[redmine::default]
    attributes:
      mysql:
        server_root_password: 'rootpass'
        server_debian_password: 'debpass'
        server_repl_password: 'replpass'
        bind_address: 'localhost'
      gitlab:
        mysql_password: 'k09vw7wa5s'
    excludes:
      - centos-6.4
